trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - doc/*
    - doc/*/*
    - .github/*
    - .github/*/*
    - .appveyor.yml
    - .travis.yml
    - CONTRIBUTORS
    - COPYING
    - README.md
    - gen-msvc-project.bat
    - setup.bat

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - doc/*
    - doc/*/*
    - .github/*
    - .github/*/*
    - .appveyor.yml
    - .travis.yml
    - CONTRIBUTORS
    - COPYING
    - README.md
    - gen-msvc-project.bat
    - setup.bat

jobs:
- job:
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Release:
        configuration: Release
      Debug:
        configuration: Debug

  steps:
  - script: |
      echo "This CI isn't tested against master, and therefore, isn't guaranteed to work. Pull requests are welcome."
      echo "If it doesn't work and you'd rather not fix it, it's recommended to use GitHub Actions CI instead."
    displayName: 'Third-Party CI Warning'

  - checkout: self
    submodules: recursive

  - script: |
      mkdir build
      cd build
      cmake .. -G "Visual Studio 16 2019" -A Win32
    displayName: 'Before build'

  - script: cmake --build . --config %configuration%
    workingDirectory: build
    displayName: 'Build'

  - script: cmake --install . --config %configuration% --prefix ../artifacts
    workingDirectory: build
    displayName: 'Prepare Files'
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))

  - task: CopyFiles@2
    displayName: 'Copy files to $(Build.ArtifactStagingDirectory)'
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))
    inputs:
      Contents: artifacts\bin\**
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: $(configuration)
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))
    displayName: Publish artifact(s)
