on:
  issues:
    types: [opened]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatically close issues that don't follow the issue template
        uses: ergo720/auto-close-issues@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login}: your issue has been automatically closed because it does not follow the issue template."  # optional property
          closed-issues-label: "invalid"  # optional property
